apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cc-service
  name: cc-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cc-service
  template:
    metadata:
      labels:
        app: cc-service
    spec:
      containers:
        - name: cc-service-container
          image: cc-service:1
          ports:
            - containerPort: 9000
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9000
            initialDelaySeconds: 15
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 3
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 5


---

apiVersion: v1
kind: Service
metadata:
  name: cc-service
spec:
  type: ClusterIP
  selector:
    app: cc-service
  ports:
    - port: 9000
      targetPort: 9000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cc-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /api/home$1$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /api/cc-service(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: cc-service
                port:
                  number: 9000